{% set name = "yaqd-omega" %}
{% set version = "2023.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/yaqd_omega-{{ version }}.tar.gz
  sha256: 571dacc475dae1e73602efee3c178f7a5894355d48ae4aab9b3d3aa3c3662720

build:
  entry_points:
    - yaqd-omega-d8200 = yaqd_omega._omega_d8200:OmegaD8200.main
    - yaqd-omega-platinum = yaqd_omega._omega_platinum:OmegaPlatinum.main
    - yaqd-omega-iseries-modbus = yaqd_omega._omega_iseries_modbus:OmegaIseriesModbus.main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - flit-core >=2,<4
    - pip
  run:
    - python >=3.7
    - yaqd-core >=2020.06.3
    - minimalmodbus
    - pymodbus >=3.1

test:
  imports:
    - yaqd_omega
  commands:
    - pip check
    - yaqd-omega-d8200 --help
    - yaqd-omega-platinum --help
    - yaqd-omega-iseries-modbus --help
  requires:
    - pip

about:
  home: https://yaq.fyi
  summary: yaq daemons for Omega Engineering hardware
  dev_url: https://github.com/yaq-project/yaqd-omega
  license: LGPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - untzag
    - ksunden
